// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Cuisines struct {
	Name   *string `json:"name"`
	URLKey *string `json:"urlKey"`
}

type FoodCharacteristics struct {
	Name         *string `json:"name"`
	IsVegetarian *bool   `json:"isVegetarian"`
}

type Schedule struct {
	ID      *string `json:"id"`
	Weekday *string `json:"weekday"`
}
